#!/usr/bin/python3

import sys
import os
import threading

if (len(sys.argv) < 2):
    exit()

src = open(sys.argv[1], "r")

lines = src.readlines();

lines = list(map(lambda line: int(line), lines))

lines.sort()


def factorize(n):
    q = 2
    while (q ** 2 <= n):
        if n % q == 0:
            break
        q += 1
    print("{:d}={:d}*{:d}".format(n, q, n // q))

i = 0
length = len(lines)

while i < length:
    t = threading.Thread(target=factorize, args=[lines[i]])
    t.start()
    i += 1
